<# 
  Extracts plain text from a .docx (ZIP + word/document.xml).
  Usage:
    .\web\scripts\extract-docx-text.ps1 -Path "web\docs\file.docx" -OutFile "web\docs\file.md"
#>
param(
  [Parameter(Mandatory = $true)][string] $Path,
  [string] $OutFile
)

$ErrorActionPreference = "Stop"
$Path = (Resolve-Path -LiteralPath $Path).Path

Add-Type -AssemblyName System.IO.Compression.FileSystem
$zip = [System.IO.Compression.ZipFile]::OpenRead($Path)
try {
  $e = $zip.GetEntry("word/document.xml")
  if (-not $e) { throw "word/document.xml not found — is this a valid .docx?" }
  $sr = New-Object System.IO.StreamReader($e.Open())
  $xml = $sr.ReadToEnd()
  $sr.Close()
} finally {
  $zip.Dispose()
}

# Pull text from w:t nodes (avoids full XML namespace setup)
$parts = [regex]::Matches($xml, '<w:t[^>]*>([^<]*)</w:t>') | ForEach-Object { $_.Groups[1].Value }
$body = ($parts -join "").Trim()

if ($OutFile) {
  $OutFile = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($OutFile)
  $header = @"
# Extracted from: $Path
<!-- Generated by extract-docx-text.ps1 — add headings and lists manually -->
"@
  Set-Content -LiteralPath $OutFile -Value ($header + "`n`n" + $body) -Encoding UTF8
  Write-Host "Wrote: $OutFile"
} else {
  $body
}
